### ISSUE TITLE
Fix mentions to "proot.me" in Downloads

### ISSUE THREAD

**Issue by rffontenelle** [proot-me/proot-me.github.io#1]
Looks like [Downloads section](https://proot-me.github.io/#downloads) still has mentions to ``proot.me`` name, which nowhere interesting. How about pointing them to a proper place or reformulating the section?

**Comment by lramage94** [comment]
https://github.com/proot-me/PRoot/issues/120

**Comment by rffontenelle** [comment]
Thanks. Closing this issue as it is duplicated and in the wrong repository (the software's repository instead of the website's).

**Comment by cmarqu** [comment]
Are you sure about closing this? This _is_ the repository for the website, and it contains the html file (https://github.com/proot-me/proot-me.github.io/blob/master/index.html) with the obsolete links...

**Comment by rffontenelle** [comment]
You are right. I'll reopen it and see how it goes.
