### ISSUE TITLE
branding

### ISSUE THREAD

**Issue by oxr463** [proot-me/proot-me.github.io#7]
<img width="106" alt="proot" src="https://user-images.githubusercontent.com/43783393/48223233-97ee1f00-e364-11e8-8c92-6552ba418b17.png">

Please update organization profile image.

**Comment by jopasserat** [comment]
hey - it doesn't fit, has to be a square

**Comment by oxr463** [comment]
Oops!

> Tip: Your profile picture should be a PNG, JPG, or GIF file under 1 MB in size. For the best quality rendering, we recommend keeping the image at about 500 by 500 pixels. --<https://help.github.com/articles/setting-your-profile-picture/>

Try this one,

![proot](https://user-images.githubusercontent.com/43783393/49589784-466f8a80-f938-11e8-92d9-92ee0b007e47.png)

**Comment by jopasserat** [comment]
perfect thx!
